# Generated by Django 5.1 on 2024-08-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('cause', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
