# Generated by Django 5.1 on 2024-08-23 10:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Index",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", ckeditor.fields.RichTextField(verbose_name="заголовок")),
                ("description", ckeditor.fields.RichTextField(verbose_name="описание")),
                ("logo", models.ImageField(upload_to="image/", verbose_name="Логотип")),
            ],
            options={
                "verbose_name": "",
                "verbose_name_plural": "Настройки главной страницы",
            },
        ),
    ]
