# Generated by Django 5.1 on 2024-08-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="index",
            name="description_2",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Описание (второй)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="index",
            name="title_2",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Заголовок (второй)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="index",
            name="title_3",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Заголовок (второй 2)"
            ),
            preserve_default=False,
        ),
    ]
