# Generated by Django 5.1 on 2024-08-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_index_description_2_index_title_2_index_title_3"),
    ]

    operations = [
        migrations.AddField(
            model_name="index",
            name="image",
            field=models.ImageField(default=1, upload_to="image/", verbose_name="фото"),
            preserve_default=False,
        ),
    ]
