# Generated by Django 5.1 on 2024-08-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_index_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Icon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=15, verbose_name="Заголовок иконки"),
                ),
                (
                    "icon",
                    models.ImageField(upload_to="image/", verbose_name="фото иконки"),
                ),
            ],
            options={
                "verbose_name": "",
                "verbose_name_plural": "Настройки иконки",
            },
        ),
    ]
