# Generated by Django 5.1 on 2024-08-23 11:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_icon2"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trips",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создание"
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="")),
            ],
        ),
        migrations.AddField(
            model_name="index",
            name="descriptions_trips",
            field=ckeditor.fields.RichTextField(
                default=1, verbose_name="описание трипс"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="index",
            name="title_trips",
            field=models.CharField(
                default=1, max_length=155, verbose_name="Заголовка ТРИПС"
            ),
            preserve_default=False,
        ),
    ]
