# Generated by Django 5.1 on 2024-08-23 12:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_trips_index_descriptions_trips_index_title_trips"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trips",
            options={"verbose_name": "", "verbose_name_plural": "Трипс"},
        ),
        migrations.AddField(
            model_name="trips",
            name="image",
            field=models.ImageField(default=1, upload_to="trips/", verbose_name="Фото"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trips",
            name="price",
            field=models.CharField(default=1, max_length=50, verbose_name="Цена"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="index",
            name="title_trips",
            field=ckeditor.fields.RichTextField(verbose_name="Заголовка ТРИПС"),
        ),
        migrations.AlterField(
            model_name="trips",
            name="title",
            field=models.CharField(max_length=155, verbose_name="Заголовка"),
        ),
    ]
