# Generated by Django 5.1 on 2024-08-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_blog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="image/", verbose_name="фото")),
                (
                    "job_title",
                    models.CharField(max_length=20, verbose_name="заголовок"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=20, verbose_name="заголовок"),
                ),
                ("descriptions", models.TextField(verbose_name="описание")),
            ],
            options={
                "verbose_name": "",
                "verbose_name_plural": "рабы",
            },
        ),
    ]
