# Generated by Django 5.1 on 2024-08-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_workers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workers",
            name="full_name",
            field=models.CharField(max_length=20, verbose_name="имя"),
        ),
        migrations.AlterField(
            model_name="workers",
            name="job_title",
            field=models.CharField(max_length=20, verbose_name="работа"),
        ),
    ]
