# Generated by Django 5.1 on 2024-08-23 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_alter_workers_full_name_alter_workers_job_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workers",
            old_name="job_title",
            new_name="title",
        ),
    ]
