# Generated by Django 5.1 on 2024-08-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_rename_job_title_workers_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="MnogoFoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="image/", verbose_name="фото")),
                ("image2", models.ImageField(upload_to="image/", verbose_name="фото2")),
            ],
            options={
                "verbose_name": "",
                "verbose_name_plural": "мини фотки",
            },
        ),
    ]
