# Generated by Django 5.1 on 2024-08-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_mnogofoto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mnogofoto",
            old_name="image",
            new_name="title",
        ),
    ]
